### ISSUE TITLE
Add documentation about end_session_endpoint

### ISSUE THREAD

**Issue by Augustin-Grenne** [msuliq/omniauth_oidc#7]
One of the excellent qualities of this gem is it's very clear and exhaustive readme/documentation. 👏  Certainly for a developer, like myself, who had very little experience with OAuth overall, this gem is a blessing.
However, one thing that seems lacking in a lot of articles, gems and OAuth documentation is the logout/end session scenario. 
Basically, my question is how do I trigger a call to the `end_session_endpoint` (it's also listed on the config_endpoint) from the application. Adding this to the readme would potentially benefit a lot of developers. 😉

**Comment by msuliq** [comment]
Hi @Augustin-Grenne, 
I have also struggled with the lack of documentation in existing gems related to omniauth with OpenID Connect. One of the reasons for writing this gem was to provide enough instructions and documentation so other developers can smoothly integrate OIDC without the need to spend the time on reading the source code and trying to understand what does it do.

I have tested and updated methods related to `end_session_endpoint` in them and addressed them [here](https://github.com/msuliq/omniauth_oidc/pull/8). Please use [gem version 0.2.3](https://rubygems.org/gems/omniauth_oidc/).

While this has been added into Readme, I will repeat myself here too.

The gem provides two configuration options to allow ending a session simultaneously with your client application and the
OIDC provider. 

In case your user has an active session both with OIDC provider and your app in the same browser and your user logs out from your applications but forgets about or keeps his session with the OIDC provider, in some cases, depending on the implementation of your application, refreshing the page with your app might result in user getting authenticated.

To use this feature for simultaneous logout, you need to provide a `logout_path` in the options and an `end_session_endpoint` in the client 
options. Here’s a sample setup:

``` ruby
  provider :oidc, {
    name: :simple_provider,
    client_options: {
      identifier: ENV['SIMPLE_PROVIDER_CLIENT_ID'],
      secret: ENV['SIMPLE_PROVIDER_SECRET'],
      config_endpoint: 'https://simpleprovider.com/1234567890/.well-known/openid-configuration',
      end_session_endpoint: 'https://simpleprovider.com/signout' # URL to end session with OIDC provider
    },
    logout_path: '/logout' # path in your application to end user session
  }
```

* `end_session_endpoint` is the URL to which your client app can redirect to log out the user from the OIDC provider's application. It can be dynamically fetched from the `config_endpoint` response if your OIDC provider specifies it there. Alternatively, you can explicitly provide it in the client options.

* `logout_path` is the URL in your Rails application that is called to terminate the current user's session.

Using these two configurations, you can ensure that when a user logs out from your application, they are also logged out
from the OIDC provider, providing a seamless logout across multiple services.

This works by calling `other_phase` on every controller request in your application. The method checks if the requested URL matches the defined `logout_path`. If it does (i.e. current user has requested to log out from your application) `other_phase` makes a redirect to the `end_session_endpoint` to terminate the user's session with the OIDC provider. Then it returns back to your application and concludes the request to end the session in your Rails application.

**Comment by msuliq** [comment]
@Augustin-Grenne has this resolved your issue?

**Comment by Augustin-Grenne** [comment]
Sorry for the late response, I logged off completely for my vacation 😉 
Thanks again for the excellent documentation. This should certainly resolve it.
